### ISSUE TITLE
Lambda tools fails when doing multiple requests to a lambda function

### ISSUE THREAD

**Issue by dentuzhik** [Testlio/lambda-tools#53]
_Before submitting a new issue, make sure no suitable duplicate exists - thank you!_

**Type:**
<:bug:>
<Please make sure the issue title starts with the type in square brackets []>

**Description:**
When making somewhat about 7 requests to a lambda function, lambda tools fail with an error:
```
build-service_1     | 2016-06-22T11:38:18.231287282Z 	-- Creating response
build-service_1     | 2016-06-22T11:38:18.252246848Z   --> DELETE /buckets/ac25cf10-ff66-4f5f-ba42-91a2e88c61e7/builds/3ccc61a4-38ed-46ca-9945-3c4b117f9737 200 11s 19b
build-service_1     | 2016-06-22T11:38:18.254408461Z
build-service_1     | 2016-06-22T11:38:18.268938209Z 	[22-06-2016 11:38:18.268] ERROR: Operation timed out
build-service_1     | 2016-06-22T11:38:18.269001909Z 		Error: Operation timed out
build-service_1     | 2016-06-22T11:38:18.269010703Z 		    at null.<anonymous> (/usr/src/app/node_modules/lambda-tools/lib/run/execution-wrapper.js:64:22)
build-service_1     | 2016-06-22T11:38:18.269015485Z 		    at Timer.listOnTimeout (timers.js:92:15)
build-service_1     | 2016-06-22T11:38:18.275794304Z 	[22-06-2016 11:38:18.275] ERROR: Operation timed out
build-service_1     | 2016-06-22T11:38:18.275818730Z 		Error: Operation timed out
build-service_1     | 2016-06-22T11:38:18.275823322Z 		    at null.<anonymous> (/usr/src/app/node_modules/lambda-tools/lib/run/execution-wrapper.js:64:22)
build-service_1     | 2016-06-22T11:38:18.275826959Z 		    at Timer.listOnTimeout (timers.js:92:15)
build-service_1     | 2016-06-22T11:38:18.278737439Z   <-- OPTIONS /buckets/ac25cf10-ff66-4f5f-ba42-91a2e88c61e7/builds
build-service_1     | 2016-06-22T11:38:18.290325434Z 	-- Creating mock response
build-service_1     | 2016-06-22T11:38:18.297963639Z   --> OPTIONS /buckets/ac25cf10-ff66-4f5f-ba42-91a2e88c61e7/builds 200 19ms 2b
build-service_1     | 2016-06-22T11:38:18.298495243Z 	-- Creating response
build-service_1     | 2016-06-22T11:38:18.307566688Z   --> DELETE /buckets/ac25cf10-ff66-4f5f-ba42-91a2e88c61e7/builds/3837f5e5-d2ec-40d3-b7b4-9379d70ec850 200 11s 19b
build-service_1     | 2016-06-22T11:38:18.309483846Z
build-service_1     | 2016-06-22T11:38:18.314777665Z
build-service_1     | 2016-06-22T11:38:18.319652875Z /usr/src/app/node_modules/lambda-tools/lib/run/execution.js:109
build-service_1     | 2016-06-22T11:38:18.322132060Z                 if (result.type === 'error') {
build-service_1     | 2016-06-22T11:38:18.322175755Z                           ^
build-service_1     | 2016-06-22T11:38:18.322736678Z
build-service_1     | 2016-06-22T11:38:18.323303643Z TypeError: Cannot read property 'type' of null
build-service_1     | 2016-06-22T11:38:18.323463284Z     at ChildProcess.<anonymous> (/usr/src/app/node_modules/lambda-tools/lib/run/execution.js:109:27)
build-service_1     | 2016-06-22T11:38:18.323486953Z     at emitTwo (events.js:100:13)
build-service_1     | 2016-06-22T11:38:18.323543901Z     at ChildProcess.emit (events.js:185:7)
build-service_1     | 2016-06-22T11:38:18.323592907Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
build-service_1     | 2016-06-22T11:38:18.367058044Z
build-service_1     | 2016-06-22T11:38:18.385595114Z npm info lifecycle build-service@2.0.0~start: Failed to exec start script
build-service_1     | 2016-06-22T11:38:18.386338225Z npm ERR! Linux 4.4.8-boot2docker
build-service_1     | 2016-06-22T11:38:18.387004880Z npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "-e" "BASE_URL=http://local.testlio:3005" "--mirror-environment"
build-service_1     | 2016-06-22T11:38:18.387632716Z npm ERR! node v5.7.0
build-service_1     | 2016-06-22T11:38:18.388339701Z npm ERR! npm  v3.6.0
build-service_1     | 2016-06-22T11:38:18.389176973Z npm ERR! code ELIFECYCLE
build-service_1     | 2016-06-22T11:38:18.391833688Z npm ERR! build-service@2.0.0 start: `lambda run "-e" "BASE_URL=http://local.testlio:3005" "--mirror-environment"`
build-service_1     | 2016-06-22T11:38:18.394527116Z npm ERR! Exit status 1
build-service_1     | 2016-06-22T11:38:18.397975161Z npm ERR!
build-service_1     | 2016-06-22T11:38:18.399016884Z npm ERR! Failed at the build-service@2.0.0 start script 'lambda run "-e" "BASE_URL=http://local.testlio:3005" "--mirror-environment"'.
build-service_1     | 2016-06-22T11:38:18.400430061Z npm ERR! Make sure you have the latest version of node.js and npm installed.
build-service_1     | 2016-06-22T11:38:18.402777939Z npm ERR! If you do, this is most likely a problem with the build-service package,
build-service_1     | 2016-06-22T11:38:18.403365721Z npm ERR! not with npm itself.
build-service_1     | 2016-06-22T11:38:18.404466793Z npm ERR! Tell the author that this fails on your system:
build-service_1     | 2016-06-22T11:38:18.405538526Z npm ERR!     lambda run "-e" "BASE_URL=http://local.testlio:3005" "--mirror-environment"
build-service_1     | 2016-06-22T11:38:18.407286131Z npm ERR! You can get information on how to open an issue for this project with:
build-service_1     | 2016-06-22T11:38:18.410043518Z npm ERR!     npm bugs build-service
build-service_1     | 2016-06-22T11:38:18.411948373Z npm ERR! Or if that isn't available, you can get their info via:
build-service_1     | 2016-06-22T11:38:18.416138952Z npm ERR!     npm owner ls build-service
build-service_1     | 2016-06-22T11:38:18.418491185Z npm ERR! There is likely additional logging output above.
build-service_1     | 2016-06-22T11:38:18.425459283Z
build-service_1     | 2016-06-22T11:38:18.426246389Z npm ERR! Please include the following file with any support request:
build-service_1     | 2016-06-22T11:38:18.426859250Z npm ERR!     /usr/src/app/npm-debug.log
```

<if bug, otherwise remove>
**Version:**
3.0.0

**Environment:**
OSX, Node v5.11.1

**Steps to reproduce:**
Make several parallel executions of lambda functions (more than 5)

**Expected result:**
It doesn't fail

**Actual result:**
It fails
</bug>

**Comment by kirstein** [comment]
Could you give some steps to reproduce the given issue? Like creating a super simple service which has that info and sharing the code?

**Comment by henrinormak** [comment]
From what I heard, it was an endpoint that timed out without producing any output, should be simple enough to create (just a long enough loop to busy-wait until timeout lapses should do it).

**Comment by henrinormak** [comment]
This should no longer occur, at least LT shouldn't crash in this particular path any more.

**Comment by henrinormak** [comment]
Forgot to add, the fix will be released along with some other stuff shortly. Not quite on npm yet.
